### ISSUE TITLE
Build failed. Process exited with code 1.  

### ISSUE THREAD

**Issue by albert0m** [tidev/hyperloop-examples#87]
I'm not sure what I'm doing wrong, but after cloning the project, and - AS IS - compile it, I get the error:

```
[ERROR]  ** BUILD FAILED **

[ERROR]  The following build commands failed:

[ERROR]  	PhaseScriptExecution My\ script\ phase /xxx/hyperloop-examples-master/build/iphone/build/Intermediates/Hyperloop_Sample.build/Debug-iphonesimulator/Hyperloop_Sample.build/Script-000000000000000000000042.sh

[ERROR]  (1 failure)
```

Even if the log-level is trace, I don't get any real error.

I'm sure I have everything set up correctly, I use cocoapods with other native applications.

**Comment by nuborian** [comment]
Same error - any news on this?

**Comment by hansemannn** [comment]
This should not be an issue anymore, sorry for that! The reason was an outdated Localytics dependency.
